version: "3"

services:
  database:
    image: "postgres:alpine"
    restart: always
    volumes:
      - "./resources/postgres:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_DB=sulten
      - POSTGRES_USER=sulten
      - POSTGRES_PASSWORD=sulten
    ports:
      - "5434:5432"
